default:
  image: cirrusci/flutter:beta

stages:
  - build
  - test
  - deploy

appbundle-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - docker
  script:
    - echo "Building the appbundle..."
    - flutter build appbundle

flutter-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags:
    - docker
  script:
    - echo "Running flutter test..."
    - flutter test

flutter-analyze-job:
  stage: test
  tags:
    - docker
  script:
    - flutter analyze

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags:
    - docker
  script:
    - echo "Deploying application... (eventually)"
